//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBInventarioCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Members = new HashSet<People>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> BossId { get; set; }
        public string PrimaryPhone { get; set; }
        public string SecondaryPhone { get; set; }
        public string Fax { get; set; }
        public string EmailAddress { get; set; }
        public string WebSite { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual People Boss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<People> Members { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }
}
